services:
  - type: web
    name: data-analyst-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: AIPIPE_TOKEN

